export const faqData: Array<{ q: string; a: string }> = [
  { q: "What services do you offer?", a: "We offer web design, UI/UX, branding, and front-end development for startups and businesses." },
  { q: "How long does a typical website take?", a: "Most small-to-medium websites take 3-6 weeks depending on scope and content readiness." },
  { q: "Do you provide ongoing support?", a: "Yes — we offer maintenance and support plans tailored to your needs, including updates and backups." },
  { q: "Can you redesign an existing website?", a: "Absolutely — we can audit your current site and provide a redesign plan that improves conversions and performance." },
  { q: "What technologies do you use?", a: "We primarily use modern React and Next.js stacks, Tailwind CSS, and headless CMS options as needed." },
  { q: "Do you handle hosting and deployment?", a: "Yes. We can deploy to Vercel, Netlify, or other hosting providers and help with domain setup." },
  { q: "Can you integrate payment gateways?", a: "We integrate Stripe, PayPal, and other common payment gateways for e-commerce and subscriptions." },
  { q: "What's the pricing model?", a: "Pricing depends on scope. We provide fixed-price proposals for projects and hourly rates for smaller tasks." },
  { q: "Do you offer SEO services?", a: "Yes — we include basic on-page SEO and can provide advanced SEO services on request." },
  { q: "Will my site be mobile-friendly?", a: "All our designs are responsive and tested across major devices and screen sizes." },
  { q: "Can you migrate content from my old site?", a: "Yes, we can migrate content and images and help reorganize content for better UX." },
  { q: "Do you create custom illustrations or graphics?", a: "We can create custom graphics or coordinate with designers to include brand assets in your site." },
  { q: "Can you connect my site to a CMS?", a: "We work with popular headless CMS options like Contentful, Sanity, Strapi, and WordPress headless setups." },
  { q: "How do we start a project?", a: "Start by contacting us with your goals; we'll schedule a discovery call and prepare a proposal." },
  { q: "What information do you need to get started?", a: "Basic brand assets, content (text/images), examples of websites you like, and project goals are ideal." },
  { q: "Do you sign NDAs?", a: "Yes — we can sign NDAs for sensitive projects before sharing detailed information." },
  { q: "Can you optimize site speed?", a: "We follow performance best practices like image optimization, code-splitting, and caching to improve speed." },
  { q: "Do you do accessibility audits?", a: "Yes — we can audit and remediate accessibility issues to meet common WCAG practices." },
  { q: "Can you create multilingual sites?", a: "We can implement multilingual support using Next.js Internationalized Routing or headless CMS translations." },
  { q: "What payment terms do you require?", a: "Typical terms are 50% upfront and 50% on delivery for small projects; enterprise terms are negotiable." },
  { q: "Do you offer discounts for startups?", a: "We sometimes offer starter packages and flexible payment plans for early-stage startups." },
  { q: "How are revisions handled?", a: "Proposals include revision rounds; we outline the number of design and content revisions in the scope." },
  { q: "Can you build custom integrations or APIs?", a: "Yes — we build custom integrations to CRMs, analytics, and third-party services as required." },
  { q: "Will I be able to update the site myself?", a: "We provide CMS access or basic guides so you can update content without developer help." },
  { q: "Do you provide training?", a: "We offer short walkthrough sessions to train your team on managing the site and CMS." },
  { q: "What happens after launch?", a: "After launch we monitor performance, fix launch issues, and can begin a maintenance plan if selected." },
  { q: "Can you improve an existing conversion funnel?", a: "Yes — we analyze analytics, run UX audits, and propose changes to improve conversion rates." },
  { q: "How do you handle images and licensing?", a: "We can use client-provided assets or licensed stock images; we ensure proper licensing is used." },
  { q: "Do you work with remote teams?", a: "Yes — we collaborate remotely and provide clear project tracking and communication during the project." },
];
